// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtU5kH6VnM_56KA7crRAqoFxt0cpP026Q',
    appId: '1:510595489754:web:0a5488d44536f5b0ce2ae3',
    messagingSenderId: '510595489754',
    projectId: 'gym-management-system-c5598',
    authDomain: 'gym-management-system-c5598.firebaseapp.com',
    storageBucket: 'gym-management-system-c5598.appspot.com',
    measurementId: 'G-H2MV381SCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxQCDQOLudBibkUiSBdJD8toZx0tE5gzI',
    appId: '1:510595489754:android:1e8514576cfd5d24ce2ae3',
    messagingSenderId: '510595489754',
    projectId: 'gym-management-system-c5598',
    storageBucket: 'gym-management-system-c5598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJrUHqBIIyM15CpskcGzDil0-BcnJbNko',
    appId: '1:510595489754:ios:87eb10a5e9f1df9fce2ae3',
    messagingSenderId: '510595489754',
    projectId: 'gym-management-system-c5598',
    storageBucket: 'gym-management-system-c5598.appspot.com',
    iosBundleId: 'com.example.gms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJrUHqBIIyM15CpskcGzDil0-BcnJbNko',
    appId: '1:510595489754:ios:87eb10a5e9f1df9fce2ae3',
    messagingSenderId: '510595489754',
    projectId: 'gym-management-system-c5598',
    storageBucket: 'gym-management-system-c5598.appspot.com',
    iosBundleId: 'com.example.gms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtU5kH6VnM_56KA7crRAqoFxt0cpP026Q',
    appId: '1:510595489754:web:b51dd862f93b1a9cce2ae3',
    messagingSenderId: '510595489754',
    projectId: 'gym-management-system-c5598',
    authDomain: 'gym-management-system-c5598.firebaseapp.com',
    storageBucket: 'gym-management-system-c5598.appspot.com',
    measurementId: 'G-YDLQST26HV',
  );
}
